name: Create Sprint Structure

on:
  workflow_dispatch:
    inputs:
      sprint_name:
        description: 'Name of the sprint (e.g., 2024-AUG)'
        required: true

jobs:
  create_sprint_structure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create sprint folder structure
      run: |
        # Define the sprint name from the workflow input
        SPRINT_NAME="${{ github.event.inputs.sprint_name }}"
        
        # Create the sprint directory and numbered subdirectories
        mkdir -p "sprints/${SPRINT_NAME}/01-todo"
        mkdir -p "sprints/${SPRINT_NAME}/02-prototyping"
        mkdir -p "sprints/${SPRINT_NAME}/03-in-progress"
        mkdir -p "sprints/${SPRINT_NAME}/04-done"
        
        # Add .gitkeep files to ensure folders are tracked by Git
        touch "sprints/${SPRINT_NAME}/01-todo/.gitkeep"
        touch "sprints/${SPRINT_NAME}/02-prototyping/.gitkeep"
        touch "sprints/${SPRINT_NAME}/03-in-progress/.gitkeep"
        touch "sprints/${SPRINT_NAME}/04-done/.gitkeep"

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add sprint structure for $SPRINT_NAME"
        git push
