name: Create Task Ticket

on:
  workflow_dispatch:
    inputs:
      task_title:
        description: 'Task Title'
        required: true
        default: 'Task_Title_Here'
      epic_name:
        description: 'Epic Name'
        required: true
        default: 'Epic_Name_Here'
      sprint:
        description: 'Sprint'
        required: true
        default: '2024-AUG'
      status:
        description: 'Task Status'
        required: true
        default: 'Task_Status_Here'
      summary_description:
        description: 'Summary Description (max 60 characters)'
        required: true
        default: 'Brief overview of the task'
      acceptance_criteria_1:
        description: 'Acceptance Criterion 1'
        required: true
        default: 'First criterion to meet'
      acceptance_criteria_2:
        description: 'Acceptance Criterion 2'
        required: false
        default: 'Second criterion to meet'
      acceptance_criteria_3:
        description: 'Acceptance Criterion 3'
        required: false
        default: 'Third criterion if needed'
      link_description:
        description: 'Link Description and URL'
        required: false
        default: 'Link_Description: http://link-to-resource.com'
      notes_and_comments:
        description: 'Notes and Comments'
        required: false
        default: 'Additional information or comments'

jobs:
  create_ticket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Task Ticket
      run: |
        SUMMARY_LENGTH=${{ github.event.inputs.summary_description }}
        if [ ${#SUMMARY_LENGTH} -gt 60 ]; then
          echo "Warning: The summary description exceeds 60 characters. Please shorten it."
          exit 1
        fi

        TASK_ID=$(date +"%Y%m%d%H%M%S")
        FILENAME="project/Demo_Project-DP/backlog/🔵DP-${TASK_ID}-${SUMMARY_LENGTH// /_}.md"

        cat <<EOF > $FILENAME
        # DP-${TASK_ID}: ${{ github.event.inputs.task_title }}
        
        - Epic = ${{ github.event.inputs.epic_name }}
        - Sprint = ${{ github.event.inputs.sprint }}
        - Status = ${{ github.event.inputs.status }}
        
        ## Description
        ${{ github.event.inputs.summary_description }}
        
        ## Acceptance Criteria
        - [ ] ${{ github.event.inputs.acceptance_criteria_1 }}
        ${{ github.event.inputs.acceptance_criteria_2:+- [ ] ${{ github.event.inputs.acceptance_criteria_2 }} }
        ${{ github.event.inputs.acceptance_criteria_3:+- [ ] ${{ github.event.inputs.acceptance_criteria_3 }} }
        
        ## Links
        - ${{ github.event.inputs.link_description }}
        
        ## Notes and Comments
        ${{ github.event.inputs.notes_and_comments }}
        EOF

    - name: Commit and Push
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add project/Demo_Project-DP/backlog/
        git commit -m "Added task $FILENAME"
        git push
