name: Choose Folder and Act

on:
  workflow_dispatch:
    inputs:
      target-folder:
        description: 'Specify the folder name manually'
        required: true

jobs:
  choose-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download folder list artifact
      uses: actions/download-artifact@v3
      with:
        name: folder-list

    - name: Verify folder exists
      run: |
        if grep -Fxq "${{ github.event.inputs['target-folder'] }}" folders.txt; then
          echo "Folder exists."
        else
          echo "Folder does not exist. Exiting."
          exit 1
        fi

    - name: Act on selected folder
      run: |
        echo "Selected folder: ${{ github.event.inputs['target-folder'] }}"
        ls ${{ github.event.inputs['target-folder'] }}

    # Add additional steps to perform actions on the selected folder
